<?php

namespace app\modules\admin\controllers;

use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\HttpException;

class SearchController extends Controller
{
    /**
     * @throws HttpException
     * @throws BadRequestHttpException
     */
    public function beforeAction($action): bool
    {
        if (!\Yii::$app->authManager->checkAccess(\Yii::$app->user->id, 'admin')) {
            throw new HttpException(403, 'У вас недостаточно прав!');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}